### ISSUE TITLE
Test samples are zero.

### ISSUE THREAD

**Issue by mememimis** [Div99/Image-Captioning#2]
Any idea why test samples are not read?

**Comment by Div99** [comment]
You'll have to be more clear, but check if you are supplying the right paths for your test samples

**Comment by mememimis** [comment]
Thank you very much.

I am getting blue 1 0.50 while you got 0.59.

The only i changed is the following : 

`def clean_descriptions(descriptions):
    # prepare translation table for removing punctuation
    **replace_punctuation = string.maketrans(string.punctuation, ' ' * len(string.punctuation))**
    for key, desc_list in descriptions.items():
        for i in range(len(desc_list)):
            desc = desc_list[i]
            # tokenize
            desc = desc.split()
            # convert to lower case
            desc = [word.lower() for word in desc]
            # remove punctuation from each token
            desc = [w.translate(replace_punctuation) for w in desc]
            # remove hanging 's' and 'a'
            desc = [word for word in desc if len(word) > 1]
            # remove tokens with numbers in them
            desc = [word for word in desc if word.isalpha()]
            # store as string
            desc_list[i] = ' '.join(desc)`

Any ideas?
